version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - database
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    restart: always

  database:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

volumes:
  database_data:

networks:
  app-network:
    driver: bridge
