
services:
  php:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - .:/app
      working_dir: /app
      depends_on:
        - database
      command: php-fpm

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - database

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
