vich_uploader:
    db_driver: orm
    storage: file_system

    mappings:
       question_images:
           uri_prefix: /images/questions
           upload_destination: '%kernel.project_dir%/public/images/questions'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
